/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int FUN = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int PRINTLN = 12;
  /** RegularExpression Id. */
  int READINPUT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int FLOAT = 16;
  /** RegularExpression Id. */
  int BOOL = 17;
  /** RegularExpression Id. */
  int VOID = 18;
  /** RegularExpression Id. */
  int APAR = 19;
  /** RegularExpression Id. */
  int FPAR = 20;
  /** RegularExpression Id. */
  int ACHAVES = 21;
  /** RegularExpression Id. */
  int FCHAVES = 22;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 23;
  /** RegularExpression Id. */
  int IGUAL = 24;
  /** RegularExpression Id. */
  int VIRGULA = 25;
  /** RegularExpression Id. */
  int MAIS = 26;
  /** RegularExpression Id. */
  int MENOS = 27;
  /** RegularExpression Id. */
  int MULT = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int MAIOR = 33;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"fun\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"return\"",
    "\"printLn\"",
    "\"readInput\"",
    "\"true\"",
    "\"false\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "<NUM>",
    "<ID>",
  };

}
